### ISSUE TITLE
To run the code in 2 GPUs, what needs to be changed in config files? 

### ISSUE THREAD

**Issue by RiyaVerma02** [markusschoen/MGNet#3]
File: MGNet-Cityscapes-Fine.yaml 
Line 21: OHEM_N_MIN: 262143  # (crop_width x crop_height / num_gpu) - 1, i.e. (1024 x 1024 / 4) -1

I see the no. of gpu based calculation here. Will changing here be sufficient ?

Great work though!

**Comment by markusschoen** [comment]
To train on 2 GPUs, you have to set `--num-gpus 2` in your training command. If your GPUs have enough memory, you should be fine without changing any config parameter. If you run out of memory, you can try one of the following:
- reduce the batch size until it fits your memory, e.g. start your train command with `SOLVER.IMS_PER_BATCH 10` or an even lower value.
- reduce the crop size: Change the INPUT.CROP.SIZE parameter in `MGNet-Cityscapes-Fine.yaml` to a lower value, e.g. `(960, 960)`. Change OHEM_N_MIN accordingly.

However, keep in mind, that both methods will likely decrease performance of the final model.
Based on our experiments, you do not have to to change OHEM_N_MIN, if you train on less than 4 GPUs, just if you change the crop size. I will update the misleading comment.
